### ISSUE TITLE
Problem with zip after "download all files"

### ISSUE THREAD

**Issue by jameszah** [holgerlembke/ESPxWebFlMgr#1]
Hi - excellent program - thanks.

I'm having a problem with the "download all files" using your basic example on 8266 with LittleFS.

The individual files all download fine, and the zip for "all files" arrives and I can open it will a text editor and see the files there, but with Windows 10 Extract All , and with WINRAR, the files are all created with 0 size and empty.  WinRAR reports the correct size on each file -- so I'm guessing a bad crc or zip format ???  WinRAR "repair archive" says it found all the files with 0 size.

I switched your program to ESP32 LittleFS a few weeks ago, and had the same problem.

I copied the example program into the src folder and built it from there using Arduino IDE - is that a problem?

Wondering if you can have a look at these:

![image](https://user-images.githubusercontent.com/36938190/104243404-bdcc4e00-541d-11eb-8ad8-967b5e4e72c8.png)
[jan11 - Copy.zip](https://github.com/holgerlembke/ESPxWebFlMgr/files/5798530/jan11.-.Copy.zip)

**Comment by jameszah** [comment]
The crc and file size are correct at the bottom of the file, but there are all zeros in the header for each component file, which Extract All and WinRAR must need.

**Comment by holgerlembke** [comment]
Well spotted, thanks. Surprisingly it somehow seems to work sometimes for most of us, me including. 

Error is a missing flag.

```
    zipFileHeader zip;
    zip.signature = 0x04034b50;
    zip.versionneeded = 0;
    zip.bitflags = 1 << 3;    // <-------------------------------- flag! Line 577 or so
    zip.comp_method = 0; // stored
    zip.lastModFileTime = 0x4fa5;
    zip.lastModFileDate = 0xe44e;
    zip.extra_field_len = 0;
```

It will be fixed online asap.
