### ISSUE TITLE
Edit on upload file not available

### ISSUE THREAD

**Issue by wchpikus** [holgerlembke/ESPxWebFlMgr#12]
HI
nice work with littlespiffs!
I have question, how to set flag E to files uploaded by www?

**Comment by holgerlembke** [comment]
Currently the Edit-function (we are talking about that?) is hard coded at

[#ifndef fileManagerEditEverything](https://github.com/holgerlembke/ESPxWebFlMgr/blob/c179cd548e8dbcd9f84c3219b95992e68d203e60/src/ESPxWebFlMgr.cpp#L328)

Easy to change.

Or switch to https://github.com/holgerlembke/ESPFMfGK with more features.

**Comment by holgerlembke** [comment]
done.
