### ISSUE TITLE
wow that looks nice

### ISSUE THREAD

**Issue by ldijkman** [holgerlembke/ESPxWebFlMgr#5]
wow that looks nice

wil try this esp filemanager

thank you   

https://github.com/ldijkman/randomnerd_esp32_wifi_manager

later i see
hmm i dont know why but i use spiffs, looks like you do not support that

**Comment by holgerlembke** [comment]
Yes, SPIFFS is deprecated. LittleFS is the solution of choice in esp32/esp8266.
