### ISSUE TITLE
LITTLEFS compiling problem

### ISSUE THREAD

**Issue by neovic1** [holgerlembke/ESPxWebFlMgr#9]
Hello. I have a problem compiling your project because IDE complains about LITTLEFS. I changed the definition from LittleFS.h to LITTLEFS.h but the problem persists. Which version of LittleFs did you use to compile? Can you post me the link to the library in Github?

**Comment by holgerlembke** [comment]
ESP8266 or ESP32?

IDE 2.0?

**Comment by neovic1** [comment]
Esp32. I used both ide, 2.0 and 1.8.16


-------------- Raúl Padilla --------------
________________________________
De: Holger Lembke ***@***.***>
Enviado: sábado, 10 de diciembre de 2022 14:33
Para: holgerlembke/ESPxWebFlMgr ***@***.***>
Cc: neovic1 ***@***.***>; Author ***@***.***>
Asunto: Re: [holgerlembke/ESPxWebFlMgr] LITTLEFS compiling problem (Issue #9)


ESP8266 or ESP32?

IDE 2.0?

**Comment by holgerlembke** [comment]
I took IDE 2.0 and ESP32 2.05 and the ESP32basicwsagzip exampple. It compiles just as it is.

Can you show some error message and more details?

**Comment by neovic1** [comment]
The error message is : ResolveLibrary(LittleFS.h)
  -> candidates: []:22: fatal error: LittleFS.h: No such file or directory

I tried to change small letters to capital letters in library name (from LittleFS.h to LITTLEFS.h). When I do that it almost compile but at the end, it gives the error: 
"exit status 1
Error compiling for ESP32 Dev Module." (I translated that from spanish to english)

I know there must be something wrong with the Littlefs library but I tried all the older versions of that library and the problem remains.
Any idea?

**Comment by holgerlembke** [comment]
Hmmm.

You can check the filename spelling at https://github.com/espressif/arduino-esp32/tree/master/libraries/LittleFS/src

Googling the error message lead to https://github.com/s00500/ESPUI/issues/156

Does that help?

**Comment by holgerlembke** [comment]
Can it be closed? Yes, it can.

**Comment by neovic1** [comment]
don't close it yet, please. Trying to find time to test what you said.

-------------- Raúl Padilla --------------
________________________________
De: Holger Lembke ***@***.***>
Enviado: lunes, 19 de diciembre de 2022 18:04
Para: holgerlembke/ESPxWebFlMgr ***@***.***>
Cc: neovic1 ***@***.***>; Author ***@***.***>
Asunto: Re: [holgerlembke/ESPxWebFlMgr] LITTLEFS compiling problem (Issue #9)


Can it be closed? Yes, it ca.

**Comment by neovic1** [comment]
First I tried the links you provided and change that line in LittleFS.cpp (the false argument) and couldn't get to compile either.
Then, I uninstalled the library LittleFS_esp32 from lorol because I thought it might be causing some interference with the one included in the arduino core. No success. 

Last thing I've done is uninstall ARDUINO IDE 2.0.2 and start from scratch, installing the new 2.0.3 ARDUINO IDE version. It seems that something has changed but still having problems. Now the compiler throws a COLLECT2.EXE ERROR. The library exists in \libraries\LittleFS and I don't know why it finds missing references to that library.
I don't know what I'm doing wrong.

C:\Users\RAUL\AppData\Local\Temp\arduino-sketch-E45830C76161D5FD6CDB27D3CBEDF141\sketch\ESP32basicwsagzip.ino.cpp.o:(.literal._Z5setupv+0x24): undefined reference to `LittleFS'
C:\Users\RAUL\AppData\Local\Temp\arduino-sketch-E45830C76161D5FD6CDB27D3CBEDF141\sketch\ESP32basicwsagzip.ino.cpp.o:(.literal._Z5setupv+0x50): undefined reference to `fs::LittleFSFS::begin(bool, char const*, unsigned char, char const*)'
C:\Users\RAUL\AppData\Local\Temp\arduino-sketch-E45830C76161D5FD6CDB27D3CBEDF141\sketch\ESP32basicwsagzip.ino.cpp.o: In function `setup()':
D:\disco duro windows xp\mis documentos\ARDUINO\libraries\ESPxWebFlMgr\examples\ESP32basicwsagzip/ESP32basicwsagzip.ino:25: undefined reference to `fs::LittleFSFS::begin(bool, char const*, unsigned char, char const*)'
C:\Users\RAUL\AppData\Local\Temp\arduino-sketch-E45830C76161D5FD6CDB27D3CBEDF141\libraries\ESPxWebFlMgr\ESPxWebFlMgr.a(ESPxWebFlMgr.cpp.o):(.literal._ZN12ESPxWebFlMgr25fileManagerFileListInsertEv+0x68): undefined reference to `fs::LittleFSFS::totalBytes()'
C:\Users\RAUL\AppData\Local\Temp\arduino-sketch-E45830C76161D5FD6CDB27D3CBEDF141\libraries\ESPxWebFlMgr\ESPxWebFlMgr.a(ESPxWebFlMgr.cpp.o):(.literal._ZN12ESPxWebFlMgr25fileManagerFileListInsertEv+0x6c): undefined reference to `fs::LittleFSFS::usedBytes()'
C:\Users\RAUL\AppData\Local\Temp\arduino-sketch-E45830C76161D5FD6CDB27D3CBEDF141\libraries\ESPxWebFlMgr\ESPxWebFlMgr.a(ESPxWebFlMgr.cpp.o): In function `ESPxWebFlMgr::totalBytes()':
d:\disco duro windows xp\mis documentos\ARDUINO\libraries\ESPxWebFlMgr\src/ESPxWebFlMgr.cpp:30: undefined reference to `fs::LittleFSFS::totalBytes()'
C:\Users\RAUL\AppData\Local\Temp\arduino-sketch-E45830C76161D5FD6CDB27D3CBEDF141\libraries\ESPxWebFlMgr\ESPxWebFlMgr.a(ESPxWebFlMgr.cpp.o): In function `ESPxWebFlMgr::usedBytes()':
d:\disco duro windows xp\mis documentos\ARDUINO\libraries\ESPxWebFlMgr\src/ESPxWebFlMgr.cpp:30: undefined reference to `fs::LittleFSFS::usedBytes()'
collect2.exe: error: ld returned 1 exit status

Usando librería WiFi con versión 1.0 en la carpeta: C:\Users\RAUL\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\libraries\WiFi 
Usando librería FS con versión 1.0 en la carpeta: C:\Users\RAUL\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\libraries\FS 
Usando librería LittleFS con versión 2.0.0 en la carpeta: D:\disco duro windows xp\mis documentos\ARDUINO\libraries\LittleFS 
Usando librería WebServer con versión 1.0 en la carpeta: C:\Users\RAUL\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\libraries\WebServer 
Usando librería ESP8266 Web File Manager con versión 1.3.5 en la carpeta: D:\disco duro windows xp\mis documentos\ARDUINO\libraries\ESPxWebFlMgr 
Usando librería SPIFFS con versión 1.0 en la carpeta: C:\Users\RAUL\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\libraries\SPIFFS 
exit status 1

Compilation error: exit status 1

**Comment by shurra85** [comment]
I have exactly the same problem. I solved it! Open the Board manager, write "esp32". Click Remove. File - Options - Additional links for the Board manager. Enter  http://arduino.esp8266.com/stable/package_esp8266com_index.json,https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json,http://digistump.com/package_digistump_index.json
Reload the IDE. Open the Board manager again, write "esp32". Click Install.

**Comment by shurra85** [comment]
![изображение](https://user-images.githubusercontent.com/91810362/225455570-e8c45bfd-d277-4542-9241-348fbd52f17f.png)

**Comment by shurra85** [comment]
![изображение](https://user-images.githubusercontent.com/91810362/225455635-22e71815-b7cc-40f3-9cd6-2027e31c9ece.png)

**Comment by holgerlembke** [comment]
I'll close this.
